### ISSUE TITLE
Phone auth without sms recieved, Faulty code?

### ISSUE THREAD

**Issue by abhimanyunaikare** [hajola/passwordless_flutter#5]
I am logged in automatically without entering the code sent via sms. i did not even received the sms code for authentication!

**Comment by hajola** [comment]
Had you logged in before?

**Comment by ShrutiAppiah** [comment]
User must have logged in previously. If they have, being logged in automatically is by design. This is why the app is called 'passwordless'. It is core functionality to allow for automatic logins.
